### ISSUE TITLE
Wrong column headers for AO-2017

### ISSUE THREAD

**Issue by marc-chan** [JeffSackmann/tennis_slam_pointbypoint#1]
Hi Jeff,

Appears that there are 67 items in each column, but only 65 column headers.

`headers = "match_id,ElapsedTime,SetNo,P1GamesWon,...,ServeWidth,ServeDepth,ReturnDepth"`
`first_row = "2017-ausopen-1101,0:00:00,1,0,...,,,"`
`print(len(headers.split(",")))`
`>>> 65`
`print(len(first_row.split(",")))`
`>>> 67`

**Comment by hgfalling** [comment]
Educated guesswork leads me to believe that the fields P1DistanceRun and P2DistanceRun need to be split in the headers into P1DistanceRun_meters and P1_DistanceRun_feet .

**Comment by JeffSackmann** [comment]
fixed
